/*
 * Combined API
 * Endpoints of CRUD of employee and displaying results of student.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.Student;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for StudentApi
 */
@Disabled
public class StudentApiTest {

    private final StudentApi api = new StudentApi();

    /**
     * Returns all student details
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void apiStudentGetTest() throws ApiException {
        List<Student> response = api.apiStudentGet();
        // TODO: test validations
    }

    /**
     * Returns student of given id
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void apiStudentIdGetTest() throws ApiException {
        Integer id = null;
        List<Student> response = api.apiStudentIdGet(id);
        // TODO: test validations
    }

}
